version: '3.8'

services:
  postgres:
    image: postgres
    container_name: URL-shorter
    environment:
      POSTGRES_DB: url_shorter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"